Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-02, with the labels that each got.

#37 🔀 :: (#36) - publishing outing current situation
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/java/com/goms/design_system/util/formatTime.kt
  core/design-system/src/main/res/drawable/ic_delete.xml
  core/design-system/src/main/res/drawable/ic_search.xml
  core/model/src/main/java/com/goms/model/enum/Major.kt
  core/ui/src/main/java/com/goms/ui/MajorText.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusText.kt
  feature/main/src/main/java/com/goms/main/component/SearchEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/SearchResultText.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModelProvider.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModelProvider.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#39 🔀 :: (#38) - write the logic outing current situation
  core/data/src/main/java/com/goms/data/di/RepositoryModule.kt
  core/data/src/main/java/com/goms/data/repository/council/CouncilRepository.kt
  core/data/src/main/java/com/goms/data/repository/council/CouncilRepositoryImpl.kt
  core/data/src/main/java/com/goms/data/repository/outing/OutingRepository.kt
  core/data/src/main/java/com/goms/data/repository/outing/OutingRepositoryImpl.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/domain/src/main/java/com/goms/domain/council/DeleteOutingUseCase.kt
  core/domain/src/main/java/com/goms/domain/outing/OutingSearchUseCase.kt
  core/network/src/main/java/com/goms/network/api/CouncilAPI.kt
  core/network/src/main/java/com/goms/network/api/OutingAPI.kt
  core/network/src/main/java/com/goms/network/datasource/council/CouncilDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/council/CouncilDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/datasource/outing/OutingDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/outing/OutingDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/di/NetworkModule.kt
  core/network/src/main/java/com/goms/network/di/RemoteDataSourceModule.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/OutingListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/SearchEmptyText.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/goms/main/viewmodel/OutingSearchUiState.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#41 🔀 :: (#40) - publishing late list
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/BottomSheetHeader.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/DatePickerBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/util/getDefaultWednesday.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/component/FilterText.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/LateListText.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#43 🔀 :: (#42) - write the logic late list
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/data/src/main/java/com/goms/data/repository/council/CouncilRepository.kt
  core/data/src/main/java/com/goms/data/repository/council/CouncilRepositoryImpl.kt
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/com/goms/design_system/util/getDefaultWednesday.kt
  core/domain/src/main/java/com/goms/domain/council/GetLateListUseCase.kt
  core/model/src/main/java/com/goms/model/response/council/LateResponse.kt
  core/network/src/main/java/com/goms/network/api/CouncilAPI.kt
  core/network/src/main/java/com/goms/network/datasource/council/CouncilDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/council/CouncilDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/main/src/main/java/com/goms/main/viewmodel/GetLateListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#49 🔀 :: (#48) - creating skeleton loading
  .idea/gradle.xml
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/BottomSheetHeader.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsBackButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/clickable/MultipleEventsCutter.kt
  core/design-system/src/main/java/com/goms/design_system/component/clickable/gomsClickable.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/ShimmerBrush.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/shimmerEffect.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/component/timer/CountdownTimer.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  feature/main/src/main/java/com/goms/main/component/FilterText.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/viewmodel/GetLateRankListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
Labels: 3️⃣ Priority: Low, ✨ Feature, ⚡️Performance

#51 🔀 :: (#13) - add qrcode function
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/data/src/main/java/com/goms/data/repository/outing/OutingRepository.kt
  core/data/src/main/java/com/goms/data/repository/outing/OutingRepositoryImpl.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_qr_scan_guide.xml
  core/domain/src/main/java/com/goms/domain/outing/OutingUseCase.kt
  core/network/src/main/java/com/goms/network/api/OutingAPI.kt
  core/network/src/main/java/com/goms/network/datasource/outing/OutingDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/outing/OutingDataSourceImpl.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/qrcode-scan/.gitignore
  feature/qrcode-scan/build.gradle.kts
  feature/qrcode-scan/consumer-rules.pro
  feature/qrcode-scan/proguard-rules.pro
  feature/qrcode-scan/src/androidTest/java/com/goms/qrcode_scan/ExampleInstrumentedTest.kt
  feature/qrcode-scan/src/main/AndroidManifest.xml
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/QrcodeScanScreen.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/component/QrcodeScanGuide.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/component/QrcodeScanPreview.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/component/QrcodeScanTopBar.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/navigation/QrcodeNavigation.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/util/QrcodeScanner.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/viewmodel/QrcodeViewModel.kt
  feature/qrcode-scan/src/test/java/com/goms/qrcode_scan/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🎨 Publishing

#52 🔀 :: (#50) - creating circular progress indicator
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  core/design-system/src/main/java/com/goms/design_system/component/indicator/GomsCircularProgressIndicator.kt
  core/network/src/main/java/com/goms/network/api/OutingAPI.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/QrcodeScanScreen.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/component/QrcodeScanGuide.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 3️⃣ Priority: Low, ✨ Feature, ⚡️Performance

#54 🔀 :: (#53) - modify set password page
  core/design-system/src/main/java/com/goms/design_system/component/indicator/GomsCircularProgressIndicator.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
Labels: 0️⃣ Priority: Critical, 🎨 Publishing, ⚡️ Simple

#56 🔀 :: (#55) - implementing push notifications
  app/build.gradle.kts
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goms/goms_android_v2/GomsNotification.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  build.gradle.kts
  core/data/src/main/java/com/goms/data/di/RepositoryModule.kt
  core/data/src/main/java/com/goms/data/repository/notification/NotificationRepository.kt
  core/data/src/main/java/com/goms/data/repository/notification/NotificationRepositoryImpl.kt
  core/domain/src/main/java/com/goms/domain/notification/SaveDeviceTokenUseCase.kt
  core/network/src/main/java/com/goms/network/api/NotificationAPI.kt
  core/network/src/main/java/com/goms/network/datasource/notification/NotificationDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/notification/NotificationDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/di/NetworkModule.kt
  core/network/src/main/java/com/goms/network/di/RemoteDataSourceModule.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Feature

#58 🔀 :: (#57) - change the gitignore file
  .gitignore
  .idea/gradle.xml
  core/notifications/src/main/java/com/goms/notifications/Ci.kt
Labels: 0️⃣ Priority: Critical, 📄 Docs, ⚡️ Simple

#60 🔀 :: (#59) - fix token reissue error
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug, ⚡️ Simple

#63 🔀 :: (#62) - get permission
  feature/main/src/main/java/com/goms/main/MainScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#66 🔀 :: (#65) - add app logo
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: 1️⃣ Priority: High, ⚡️ Simple

#67 🔀 :: (#61) - add qrcode generation function
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/data/src/main/java/com/goms/data/repository/council/CouncilRepository.kt
  core/data/src/main/java/com/goms/data/repository/council/CouncilRepositoryImpl.kt
  core/domain/src/main/java/com/goms/domain/council/GetOutingUUIDUseCase.kt
  core/model/src/main/java/com/goms/model/response/council/OutingUUIDResponse.kt
  core/network/src/main/java/com/goms/network/api/CouncilAPI.kt
  core/network/src/main/java/com/goms/network/datasource/council/CouncilDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/council/CouncilDataSourceImpl.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/qrcode-scan/src/main/java/com/goms/qrcode_scan/navigation/QrcodeNavigation.kt
  feature/qrcode/.gitignore
  feature/qrcode/build.gradle.kts
  feature/qrcode/consumer-rules.pro
  feature/qrcode/proguard-rules.pro
  feature/qrcode/src/androidTest/java/com/goms/qrcode_scan/ExampleInstrumentedTest.kt
  feature/qrcode/src/main/AndroidManifest.xml
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateText.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateTimer.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanGuide.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanPreview.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanTopBar.kt
  feature/qrcode/src/main/java/com/goms/qrcode/navigation/QrcodeNavigation.kt
  feature/qrcode/src/main/java/com/goms/qrcode/util/QrcodeGenerator.kt
  feature/qrcode/src/main/java/com/goms/qrcode/util/QrcodeScanner.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/GetOutingUUIDUiState.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/qrcode/src/test/java/com/goms/qrcode_scan/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🎨 Publishing
