Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-06, with the labels that each got.

#233 🔀 :: (#232) - current permission check function
  core/datastore/src/main/java/com/goms/datastore/datasource/setting/SettingDataSourceImpl.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#238 🔀 :: (#237) - change base url
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#240 🔀 :: (#240) - Release 1.2.4
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#241 🔀 :: (#241) - release 1.2.4
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#244 🔀 :: (#243) - handling exceptions sing up
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#246 🔀 :: (#245) - handling error during duplicate refresh call
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#248 🔀 :: (#242) - setting screen modify
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingButton.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🎨 Publishing

#249 🔀 :: (#247) - add email resend dialog
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/find-password/src/main/res/values/strings.xml
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, ✨ Feature

#252 🔀 :: (#250) - add a maximum character limit
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#253 🔀 :: (#253) - add upload image loading dialog
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#255 🔀 :: (#254) - update version 1.2.5
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#256 🔀 :: (#256) - release 1.2.5
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/find-password/src/main/res/values/strings.xml
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingButton.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/res/values/strings.xml
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#258 🔀 :: (#257) - change back navigation
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
Labels: 1️⃣ Priority: High, ⚡️Performance

#260 🔀 :: (#259) - change outing exception text
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/qrcode/src/main/res/values/strings.xml
Labels: 1️⃣ Priority: High, ⚡️ Simple

#262 🔀 :: (#261) - add spacer
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/BottomSheetHeader.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/ProfileBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsBackButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsOneButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsTwoButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/spacer/GomsSpacer.kt
  core/design-system/src/main/java/com/goms/design_system/component/spacer/SpacerSize.kt
  core/ui/src/main/java/com/goms/ui/GomsRoleBackButton.kt
  core/ui/src/main/java/com/goms/ui/SwitchSelectorBottomSheet.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/component/LoginText.kt
  feature/main/src/main/java/com/goms/main/AdminMenuScreen.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/AdminMenuList.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/LateListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/SearchEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateText.kt
  feature/re-password/src/main/java/com/goms/re_password/PasswordCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/WithdrawalScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingButton.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector

#266 🔀 :: (#236) - add composable preview
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/BottomSheetHeader.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/DatePickerBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/ProfileBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsBackButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsOneButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsTwoButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/design-system/src/main/java/com/goms/design_system/component/indicator/GomsCircularProgressIndicator.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/shimmerEffect.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/RowLinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/theme/GomsTheme.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/goms/ui/GomsFloatingButton.kt
  core/ui/src/main/java/com/goms/ui/GomsRoleBackButton.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  core/ui/src/main/java/com/goms/ui/SwitchSelectorBottomSheet.kt
  core/ui/src/main/java/com/goms/ui/rememberMultiplePermissionsStateSafe.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/main/src/main/java/com/goms/main/AdminMenuScreen.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/MainTimeProfileCard.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanGuide.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanTopBar.kt
  feature/re-password/src/main/java/com/goms/re_password/PasswordCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/WithdrawalScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingSwitchComponent.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#268 🔀 :: (#267) - add too many request exception
  core/common/src/main/java/com/goms/common/exception/HttpException.kt
  core/common/src/main/java/com/goms/common/network/errorHandling.kt
  core/network/src/main/java/com/goms/network/util/GomsApiHandler.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/FindPasswordViewmodel.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/uistate/SendNumberUiState.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/uistate/VerifyNumberUiState.kt
  feature/find-password/src/main/res/values/strings.xml
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SendNumberUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/VerifyNumberUiState.kt
  feature/sign-up/src/main/res/values/strings.xml
Labels: 0️⃣ Priority: Critical, ✨ Feature

#270 🔀 :: (#269) - change password regex
  core/design-system/src/main/res/values/strings.xml
  core/model/src/main/java/com/goms/model/util/Regex.kt
Labels: 0️⃣ Priority: Critical, 🔨 Refector

#271 🔀 :: (#265) - fixed bug with image rotating
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  feature/setting/src/main/java/com/goms/setting/util/ImageRotator.kt
  feature/setting/src/main/java/com/goms/setting/util/MultipartConverter.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#274 🔀 :: (#273) - prevent text field spaces from entering
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#276 🔀 :: (#275) - cancel when the filter option is active if pressed again
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature
