Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-03, with the labels that each got.

#72 🔀 :: (#71) - change password regular expression
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/util/isStrongPassword.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#74 🔀 :: (#73) - handling errors
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  core/common/src/main/java/com/goms/common/network/.gitkeep
  core/common/src/main/java/com/goms/common/network/errorHandling.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/util/isStrongPassword.kt
  core/ui/src/main/java/com/goms/ui/createToast.kt
  core/ui/src/main/java/com/goms/ui/isStrongEmail.kt
  core/ui/src/main/java/com/goms/ui/isStrongPassword.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginUiState.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#76 🔀 :: (#75) - fix get default wednesday function
  .idea/inspectionProfiles/Project_Default.xml
  core/design-system/src/main/java/com/goms/design_system/util/getDefaultWednesday.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#78 🔀 :: (#77) - increase click effect visibility
  core/design-system/src/main/java/com/goms/design_system/component/clickable/gomsClickable.kt
  core/design-system/src/main/java/com/goms/design_system/theme/ColorTheme.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/DarkColor.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/LightColor.kt
  core/design-system/src/main/java/com/goms/design_system/util/systemUi.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector

#80 🔀 :: (#79) - handling exception
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/common/src/main/java/com/goms/common/network/errorHandling.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/navigation/LoginNavigation.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginUiState.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanTopBar.kt
  feature/qrcode/src/main/java/com/goms/qrcode/navigation/QrcodeNavigation.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/OutingUiState.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/navigation/SignUpNavigation.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/VerifyNumberUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#82 🔀 :: (#81) - add filter initialization
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ⚡️ Simple

#84 🔀 :: (#83) - fix setcontent
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#86 🔀 :: (#85) - pull down to refresh
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ✨ Feature, ⚡️Performance

#88 🔀 :: (#87) - refactoring initialization function
  .idea/gradle.xml
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/VerifyNumberUiState.kt
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector

#90 🔀 :: (#70) - setting page publishing
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/java/com/goms/design_system/util/Shadow.kt
  core/design-system/src/main/res/drawable/ic_change_profile.xml
  core/design-system/src/main/res/drawable/ic_chevron_down.xml
  core/design-system/src/main/res/drawable/ic_chevron_right.xml
  core/design-system/src/main/res/drawable/ic_chevron_up.xml
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/setting/.gitignore
  feature/setting/build.gradle.kts
  feature/setting/consumer-rules.pro
  feature/setting/proguard-rules.pro
  feature/setting/src/androidTest/java/com/goms/setting/ExampleInstrumentedTest.kt
  feature/setting/src/main/AndroidManifest.xml
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/PasswardChangeButton.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingSwitchComponent.kt
  feature/setting/src/main/java/com/goms/setting/navigation/SettingNavigation.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/GetProfileUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModelProvider.kt
  feature/setting/src/test/java/com/goms/setting/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, 🎨 Publishing

#92 🔀 :: (#91) - add goms click
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  feature/setting/src/main/java/com/goms/setting/component/PasswardChangeButton.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#96 🔀 :: (#95) - apply drop down to sign up
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/model/src/main/java/com/goms/model/enum/Major.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectGenderDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectMajorDropDown.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#100 🔀 :: (#99) - custom interval to gomsClickable
  core/design-system/src/main/java/com/goms/design_system/component/clickable/MultipleEventsCutter.kt
  core/design-system/src/main/java/com/goms/design_system/component/clickable/gomsClickable.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ⚡️ Simple

#101 🔀 :: (#93) - add change profile
  app/src/main/AndroidManifest.xml
  core/data/src/main/java/com/goms/data/repository/account/AccountRepository.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepositoryImpl.kt
  core/domain/build.gradle.kts
  core/domain/src/main/java/com/goms/domain/account/UploadProfileImageUseCase.kt
  core/network/src/main/java/com/goms/network/api/AccountAPI.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSourceImpl.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/util/MultipartConverter.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/ProfileImageUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#103 🔀 :: (#64) reset password publishing
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanTopBar.kt
  feature/qrcode/src/main/java/com/goms/qrcode/navigation/QrcodeNavigation.kt
  feature/re-password/.gitignore
  feature/re-password/build.gradle.kts
  feature/re-password/consumer-rules.pro
  feature/re-password/proguard-rules.pro
  feature/re-password/src/androidTest/java/com/goms/re_password/ExampleInstrumentedTest.kt
  feature/re-password/src/main/AndroidManifest.xml
  feature/re-password/src/main/java/com/goms/re_password/EmailCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/NumberScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/component/NumberText.kt
  feature/re-password/src/main/java/com/goms/re_password/component/RePasswordText.kt
  feature/re-password/src/main/java/com/goms/re_password/navigation/RePasswordNavigation.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodelProvider.kt
  feature/re-password/src/test/java/com/goms/re_password/ExampleUnitTest.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/navigation/SettingNavigation.kt
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🎨 Publishing

#98 🔀 :: (#89) - apply mendable
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build.gradle.kts
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/login/src/main/java/com/goms/login/viewmodel/SaveTokenUiState.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/data/LateData.kt
  feature/main/src/main/java/com/goms/main/data/OutingData.kt
  feature/main/src/main/java/com/goms/main/data/ProfileData.kt
  feature/main/src/main/java/com/goms/main/data/RankData.kt
  feature/main/src/main/java/com/goms/main/data/StudentData.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModelProvider.kt
  feature/re-password/src/main/java/com/goms/re_password/EmailCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/NumberScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/navigation/RePasswordNavigation.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodelProvider.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/VerifyNumberUiState.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/data/ProfileData.kt
  feature/setting/src/main/java/com/goms/setting/navigation/SettingNavigation.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModelProvider.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectGenderDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectMajorDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/navigation/SignUpNavigation.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SendNumberUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModelProvider.kt
  gradle/libs.versions.toml
Labels: 3️⃣ Priority: Low, ⚡️Performance

#106 🔀 :: (#105) - remove unused modules
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goms/goms_android_v2/GomsApplication.kt
  app/src/main/java/com/goms/goms_android_v2/di/module/.gitkeep
  core/datastore-proto/.gitignore
  core/datastore-proto/build.gradle.kts
  core/datastore-proto/consumer-rules.pro
  core/datastore-proto/proguard-rules.pro
  core/datastore-proto/src/androidTest/java/com/goms/datastore_proto/ExampleInstrumentedTest.kt
  core/datastore-proto/src/main/AndroidManifest.xml
  core/datastore-proto/src/test/java/com/goms/datastore_proto/ExampleUnitTest.kt
  core/notifications/.gitignore
  core/notifications/build.gradle.kts
  core/notifications/src/main/java/com/goms/notifications/.gitkeep
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector

#107 🔀 :: (#102) - select theme
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/design-system/src/main/java/com/goms/design_system/theme/GomsTheme.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectGenderDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectMajorDropDown.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#110 🔀 :: (#109) - change the logic to get role
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ⚡️ Simple

#114 🔀 :: (#113) - refactoring a small code
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsAppState.kt
  build.gradle.kts
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector

#115 🔀 :: (#104) - reset password
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepository.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepositoryImpl.kt
  core/domain/src/main/java/com/goms/domain/account/RePasswordUseCase.kt
  core/model/src/main/java/com/goms/model/request/account/RePasswordRequest.kt
  core/network/src/main/java/com/goms/network/api/AccountAPI.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSourceImpl.kt
  feature/re-password/src/main/java/com/goms/re_password/EmailCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/navigation/RePasswordNavigation.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/SendNumberUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#119 🔀 :: (#118) - qrcode run immediately
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/domain/src/main/java/com/goms/domain/setting/SetQrcodeUseCase.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingSwitchComponent.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#124 🔀 :: (#123) - reflect the changes in the main part design
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_coffee.xml
  core/design-system/src/main/res/drawable/ic_fire.xml
  core/design-system/src/main/res/drawable/ic_search.xml
  core/ui/src/main/java/com/goms/ui/GomsRoleBackButton.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/FilterText.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/LateListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/SearchEmptyText.kt
Labels: 0️⃣ Priority: Critical, 🎨 Publishing

#126 🔀 :: (#125) - reflect the changes in the remaining part design
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/ShimmerBrush.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/LightColor.kt
  core/design-system/src/main/java/com/goms/design_system/util/systemUi.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/PasswardChangeButton.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
Labels: 0️⃣ Priority: Critical, 🎨 Publishing

#128 🔀 :: (#127) - add logout dialog
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsOneButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsTwoButtonDialog.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/PasswardChangeButton.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#132 🔀 :: (#131) - change version
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#136 🔀 :: (#135) - fix navigation afterimage error
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
Labels: 1️⃣ Priority: High, 🐞 Bug

#138 🔀 :: (#137) - adjustment of spacing
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateTimer.kt
Labels: 2️⃣ Priortiy: Medium, ⚡️ Simple

#140 🔀 :: (#139) - change qr loading image
  core/design-system/src/main/java/com/goms/design_system/component/timer/CountdownTimer.kt
  core/design-system/src/main/res/drawable/ic_qrcode_load.xml
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateTimer.kt
Labels: 3️⃣ Priority: Low, ⚡️ Simple
