Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-08, with the labels that each got.

#303 🔀 :: (#302) - add custom event to firebase analytics
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/analytics/.gitignore
  core/analytics/build.gradle.kts
  core/analytics/consumer-rules.pro
  core/analytics/proguard-rules.pro
  core/analytics/src/androidTest/java/com/goms/analytics/ExampleInstrumentedTest.kt
  core/analytics/src/main/AndroidManifest.xml
  core/analytics/src/main/java/com/goms/analytics/AnalyticsEvent.kt
  core/analytics/src/main/java/com/goms/analytics/AnalyticsHelper.kt
  core/analytics/src/main/java/com/goms/analytics/FirebaseAnalyticsHelper.kt
  core/analytics/src/main/java/com/goms/analytics/NoOpAnalyticsHelper.kt
  core/analytics/src/main/java/com/goms/analytics/UiHelper.kt
  core/analytics/src/main/java/com/goms/analytics/di/AnalyticsModule.kt
  core/analytics/src/test/java/com/goms/analytics/ExampleUnitTest.kt
  core/ui/build.gradle.kts
  core/ui/src/main/java/com/goms/ui/AnalyticsExtension.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/res/values/strings.xml
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/res/values/strings.xml
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 1️⃣ Priority: High, ✨ Feature

#307 🔀 :: (#306) - overdraw optimization
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple, ⚡️Performance

#309 🔀 :: (#308) - fix app gradle error
  app/build.gradle.kts
  gradle/libs.versions.toml
Labels: 3️⃣ Priority: Low, 🐞 Bug

#311 🔀 :: (310) - Remove unused parameters
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector
