Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-01, with the labels that each got.

#6 🔀 :: (#5) - design system setting
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/ui/theme/Color.kt
  app/src/main/java/com/goms/goms_android_v2/ui/theme/Theme.kt
  app/src/main/java/com/goms/goms_android_v2/ui/theme/Type.kt
  core/design-system/src/main/java/com/goms/design_system/theme/.gitkeep
  core/design-system/src/main/java/com/goms/design_system/theme/ColorTheme.kt
  core/design-system/src/main/java/com/goms/design_system/theme/GomsTheme.kt
  core/design-system/src/main/java/com/goms/design_system/theme/GomsTypography.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/DarkColor.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/LightColor.kt
  core/design-system/src/main/java/com/goms/design_system/util/.gitkeep
  core/design-system/src/main/java/com/goms/design_system/util/systemUi.kt
  core/design-system/src/main/res/font/pretendard_black.otf
  core/design-system/src/main/res/font/pretendard_bold.otf
  core/design-system/src/main/res/font/pretendard_extrabold.otf
  core/design-system/src/main/res/font/pretendard_extralight.otf
  core/design-system/src/main/res/font/pretendard_light.otf
  core/design-system/src/main/res/font/pretendard_medium.otf
  core/design-system/src/main/res/font/pretendard_regular.otf
  core/design-system/src/main/res/font/pretendard_semibold.otf
  core/design-system/src/main/res/font/pretendard_thin.otf
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#8 🔀 :: (#7) - publishing splash
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/res/values/themes.xml
  core/design-system/src/main/java/com/goms/design_system/util/systemUi.kt
  core/design-system/src/main/res/drawable/ic_goms.xml
  core/design-system/src/main/res/drawable/ic_splash.xml
Labels: 1️⃣ Priority: High, 🎨 Publishing

#10 🔀 :: (#9) - publishing login
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/TopLevelDestination.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsAppState.kt
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/com/goms/design_system/component/.gitkeep
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/modifier/MultipleEventsCutter.kt
  core/design-system/src/main/java/com/goms/design_system/component/modifier/gomsClickable.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/view/GAuthWebView.kt
  core/design-system/src/main/java/com/goms/design_system/icon/.gitkeep
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/java/com/goms/design_system/util/lockScreenOrientation.kt
  feature/login/src/main/java/com/goms/login/.gitkeep
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/component/LoginText.kt
  feature/login/src/main/java/com/goms/login/navigation/LoginNavigation.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: 1️⃣ Priority: High, 🎨 Publishing

#12 🔀 :: (#11) - publishing number login
  .idea/gradle.xml
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/ButtonState.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/component/timer/CountdownTimer.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/DarkColor.kt
  core/design-system/src/main/java/com/goms/design_system/theme/color/LightColor.kt
  core/design-system/src/main/java/com/goms/design_system/util/keyboardAsState.kt
  core/design-system/src/main/res/drawable/ic_gauth.xml
  feature/login/src/main/java/com/goms/login/EmailLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/NumberLoginScreen.kt
  feature/login/src/main/java/com/goms/login/component/NumberLoginText.kt
  feature/login/src/main/java/com/goms/login/navigation/LoginNavigation.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High, 🎨 Publishing

#16 🔀 :: (#15) - architectural restructuring
  .idea/gradle.xml
  .idea/misc.xml
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  core/data/repository/build.gradle.kts
  core/data/repository/src/androidTest/java/com/goms/repository/ExampleInstrumentedTest.kt
  core/data/repository/src/test/java/com/goms/repository/ExampleUnitTest.kt
  core/data/src/main/java/com/goms/data/repository/.gitkeep
  core/datastore-proto/.gitignore
  core/datastore-proto/build.gradle.kts
  core/datastore-proto/consumer-rules.pro
  core/datastore-proto/proguard-rules.pro
  core/datastore-proto/src/androidTest/java/com/goms/datastore_proto/ExampleInstrumentedTest.kt
  core/datastore-proto/src/main/AndroidManifest.xml
  core/datastore-proto/src/main/java/com/goms/datastore_proto/.gitkeep
  core/datastore-proto/src/test/java/com/goms/datastore_proto/ExampleUnitTest.kt
  core/datastore/.gitignore
  core/datastore/build.gradle.kts
  core/datastore/consumer-rules.pro
  core/datastore/proguard-rules.pro
  core/datastore/src/androidTest/java/com/goms/datastore/ExampleInstrumentedTest.kt
  core/datastore/src/main/AndroidManifest.xml
  core/datastore/src/main/java/com/goms/datastore/.gitkeep
  core/datastore/src/test/java/com/goms/datastore/ExampleUnitTest.kt
  core/network/.gitignore
  core/network/build.gradle.kts
  core/network/consumer-rules.pro
  core/network/proguard-rules.pro
  core/network/src/androidTest/java/com/goms/network/ExampleInstrumentedTest.kt
  core/network/src/main/AndroidManifest.xml
  core/network/src/main/java/com/goms/network/api/.gitkeep
  core/network/src/main/java/com/goms/network/datasource/.gitkeep
  core/network/src/main/java/com/goms/network/util/.gitkeep
  core/network/src/test/java/com/goms/network/ExampleUnitTest.kt
  core/notifications/.gitignore
  core/notifications/build.gradle.kts
  core/notifications/src/main/java/com/goms/notifications/.gitkeep
  core/notifications/src/main/java/com/goms/notifications/Ci.kt
  core/ui/.gitignore
  core/ui/build.gradle.kts
  core/ui/consumer-rules.pro
  core/ui/proguard-rules.pro
  core/ui/src/androidTest/java/com/goms/ui/ExampleInstrumentedTest.kt
  core/ui/src/main/AndroidManifest.xml
  core/ui/src/main/java/com/goms/ui/.gitkeep
  core/ui/src/test/java/com/goms/ui/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#19 🔀 :: (#14) - write the logic login
  core/common/src/main/java/com/goms/common/Event.kt
  core/common/src/main/java/com/goms/common/errorHandling.kt
  core/common/src/main/java/com/goms/common/exception/HttpException.kt
  core/common/src/main/java/com/goms/common/exception/InternetException.kt
  core/common/src/main/java/com/goms/common/exception/TokenExpirationException.kt
  core/data/src/main/java/com/goms/data/di/RepositoryModule.kt
  core/data/src/main/java/com/goms/data/repository/.gitkeep
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/goms/domain/auth/LoginUseCase.kt
  core/domain/src/main/java/com/goms/domain/exception/.gitkeep
  core/domain/src/main/java/com/goms/domain/usecase/login/.gitkeep
  core/domain/src/main/java/com/goms/domain/usecase/sign_up/.gitkeep
  core/model/src/main/java/com/goms/model/Ci.kt
  core/model/src/main/java/com/goms/model/request/auth/LoginRequest.kt
  core/model/src/main/java/com/goms/model/request/login/.gitkeep
  core/model/src/main/java/com/goms/model/response/auth/LoginResponse.kt
  core/model/src/main/java/com/goms/model/response/login/.gitkeep
  core/network/build.gradle.kts
  core/network/src/main/java/com/goms/network/api/.gitkeep
  core/network/src/main/java/com/goms/network/api/AuthAPI.kt
  core/network/src/main/java/com/goms/network/datasource/.gitkeep
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/di/NetworkModule.kt
  core/network/src/main/java/com/goms/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/goms/network/util/.gitkeep
  core/network/src/main/java/com/goms/network/util/GomsApiHandler.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/AuthViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#21 🔀 :: (#20) - change json to moshi
  app/src/main/AndroidManifest.xml
  build-logic/convention/src/main/kotlin/JvmLibraryConventionPlugin.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/goms/model/request/auth/LoginRequest.kt
  core/model/src/main/java/com/goms/model/response/auth/LoginResponse.kt
  core/network/src/main/java/com/goms/network/di/NetworkModule.kt
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, 🔨 Refector

#25 🔀 :: (#24) - publishing sign up
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsBackButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_back.xml
  core/design-system/src/main/res/drawable/ic_close.xml
  core/model/src/main/java/com/goms/model/enum/Gender.kt
  core/model/src/main/java/com/goms/model/enum/Major.kt
  core/model/src/main/java/com/goms/model/model/.gitkeep
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/navigation/LoginNavigation.kt
  feature/sign-up/src/main/java/com/goms/sign_up/.gitkeep
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/NumberText.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/PasswordText.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SignUpText.kt
  feature/sign-up/src/main/java/com/goms/sign_up/navigation/SignUpNavigation.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High, 🎨 Publishing

#29 🔀 :: (#28) - write the logic login
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  core/model/src/main/java/com/goms/model/enum/Authority.kt
  core/model/src/main/java/com/goms/model/request/auth/LoginRequest.kt
  core/model/src/main/java/com/goms/model/response/auth/LoginResponse.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/AuthViewModel.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginUiState.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#31 🔀 :: (#30) - write the logic sign up
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsAppState.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/util/isStrongPassword.kt
  core/domain/src/main/java/com/goms/domain/auth/SendNumberUseCase.kt
  core/domain/src/main/java/com/goms/domain/auth/SighUpUseCase.kt
  core/domain/src/main/java/com/goms/domain/auth/VerifyNumberUseCase.kt
  core/model/src/main/java/com/goms/model/request/auth/SendNumberRequest.kt
  core/model/src/main/java/com/goms/model/request/auth/SignUpRequest.kt
  core/network/src/main/java/com/goms/network/api/AuthAPI.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/navigation/SignUpNavigation.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SharedViewModelProvider.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#33 🔀 :: (#32) - publishing main
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/TopLevelDestination.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsAppState.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_goms_text.xml
  core/design-system/src/main/res/drawable/ic_person.xml
  core/design-system/src/main/res/drawable/ic_qr_create.xml
  core/design-system/src/main/res/drawable/ic_qr_scan.xml
  core/design-system/src/main/res/drawable/ic_setting.xml
  core/ui/src/main/java/com/goms/ui/GomsFloatingButton.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  core/ui/src/main/java/com/goms/ui/MainLateCard.kt
  core/ui/src/main/java/com/goms/ui/MainOutingCard.kt
  core/ui/src/main/java/com/goms/ui/MainProfileCard.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/login/src/main/java/com/goms/login/navigation/LoginNavigation.kt
  feature/main/.gitignore
  feature/main/build.gradle.kts
  feature/main/consumer-rules.pro
  feature/main/proguard-rules.pro
  feature/main/src/androidTest/java/com/goms/main/ExampleInstrumentedTest.kt
  feature/main/src/main/AndroidManifest.xml
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
  feature/main/src/test/java/com/goms/main/ExampleUnitTest.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  settings.gradle.kts
Labels: 1️⃣ Priority: High, 🎨 Publishing

#35 🔀 :: (#34) - write the logic main
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  core/data/src/main/java/com/goms/data/di/RepositoryModule.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepository.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepositoryImpl.kt
  core/data/src/main/java/com/goms/data/repository/late/LateRepository.kt
  core/data/src/main/java/com/goms/data/repository/late/LateRepositoryImpl.kt
  core/data/src/main/java/com/goms/data/repository/outing/OutingRepository.kt
  core/data/src/main/java/com/goms/data/repository/outing/OutingRepositoryImpl.kt
  core/datastore/src/main/java/com/goms/datastore/AuthTokenDataSource.kt
  core/design-system/src/main/res/drawable/ic_profile.xml
  core/domain/src/main/java/com/goms/domain/account/GetProfileUseCase.kt
  core/domain/src/main/java/com/goms/domain/late/GetLateRankListUseCase.kt
  core/domain/src/main/java/com/goms/domain/outing/GetOutingCountUseCase.kt
  core/domain/src/main/java/com/goms/domain/outing/GetOutingListUseCase.kt
  core/model/src/main/java/com/goms/model/enum/Major.kt
  core/model/src/main/java/com/goms/model/response/account/ProfileResponse.kt
  core/model/src/main/java/com/goms/model/response/late/RankResponse.kt
  core/model/src/main/java/com/goms/model/response/outing/CountResponse.kt
  core/model/src/main/java/com/goms/model/response/outing/OutingResponse.kt
  core/network/src/main/java/com/goms/network/api/AccountAPI.kt
  core/network/src/main/java/com/goms/network/api/LateAPI.kt
  core/network/src/main/java/com/goms/network/api/OutingAPI.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/datasource/late/LateDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/late/LateDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/datasource/outing/OutingDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/outing/OutingDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/di/NetworkModule.kt
  core/network/src/main/java/com/goms/network/di/RemoteDataSourceModule.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  core/ui/src/main/java/com/goms/ui/MainLateCard.kt
  core/ui/src/main/java/com/goms/ui/MainOutingCard.kt
  core/ui/src/main/java/com/goms/ui/MainProfileCard.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/viewmodel/GetLateRankListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/GetOutingCountUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/GetOutingListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/GetProfileUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
Labels: 1️⃣ Priority: High, ✨ Feature
