Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-07, with the labels that each got.

#281 🔀 :: (#280) - improve bar code recognition performance new
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanPreview.kt
  feature/qrcode/src/main/java/com/goms/qrcode/util/QrcodeScanner.kt
Labels: 0️⃣ Priority: Critical, ⚡️Performance

#282 🔀 :: (#279) - optimizing compose
  app/src/main/java/com/goms/goms_android_v2/GomsNotification.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/ProfileBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/clickable/gomsClickable.kt
  core/design-system/src/main/java/com/goms/design_system/component/indicator/GomsCircularProgressIndicator.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/ShimmerBrush.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/shimmerEffect.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/timer/CountdownTimer.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/AdminMenuList.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateTimer.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector, ⚡️Performance

#284 🔀 :: (#283) - update mlkit version
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, 🌏 Deploy, ⚙ Setting, ⚡️ Simple

#285 🔀 :: (#256) - release 1.2.7
  app/src/main/java/com/goms/goms_android_v2/GomsNotification.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  core/design-system/build.gradle.kts
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/ProfileBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/clickable/gomsClickable.kt
  core/design-system/src/main/java/com/goms/design_system/component/indicator/GomsCircularProgressIndicator.kt
  core/design-system/src/main/java/com/goms/design_system/component/lottie/AnimatedLottie.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/ShimmerBrush.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/shimmerEffect.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/timer/CountdownTimer.kt
  core/design-system/src/main/res/raw/blacklist.json
  core/design-system/src/main/res/raw/outing_failed.json
  core/design-system/src/main/res/raw/outing_success.json
  core/design-system/src/main/res/raw/return_success.json
  core/ui/src/main/java/com/goms/ui/isAfterReturnTime.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/AdminMenuList.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateTimer.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeResultDescriptionText.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeResultDialog.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeResultText.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeScanPreview.kt
  feature/qrcode/src/main/java/com/goms/qrcode/util/QrcodeScanner.kt
  feature/qrcode/src/main/res/values/strings.xml
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  gradle/libs.versions.toml
Labels: 🌏 Deploy

#287 🔀 :: (#286) - add blank characters to resource keys
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  core/datastore/src/main/java/com/goms/datastore/datasource/auth/AuthTokenDataSourceImpl.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/model/src/main/java/com/goms/model/util/ResourceKeys.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/FindPasswordViewmodel.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector

#289 🔀 :: (#288) - customizing a screen change animation
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
Labels: 1️⃣ Priority: High, ✨ Feature

#291 🔀 :: (#290) - change the date to appear on the late list
  core/design-system/src/main/java/com/goms/design_system/util/formatDate.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/LocalDateText.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#292 Fix/263 switch button non change error
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  feature/setting/build.gradle.kts
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, 🐞 Bug, ✨ Feature

#294 🔀 :: (#293) - separate email authentication number request logic
  core/model/src/main/java/com/goms/model/enum/EmailStatus.kt
  core/model/src/main/java/com/goms/model/request/auth/SendNumberRequestModel.kt
  core/network/src/main/java/com/goms/network/dto/request/auth/SendNumberRequest.kt
  core/network/src/main/java/com/goms/network/mapper/request/auth/SendNumverRequestMapper.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/FindPasswordViewmodel.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/uistate/SendNumberUiState.kt
  feature/find-password/src/main/res/values/strings.xml
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#296 🔀 :: (#295) - update version 1.2.8
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#299 🔀 :: (#298) - save device token as datastore
  app/src/main/java/com/goms/goms_android_v2/GomsNotification.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector, ⚡️Performance

#301 🔀 :: (#300) - create a preview custom annotation
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/BottomSheetHeader.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/DatePickerBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/MultipleSelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/ProfileBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsOneButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/dialog/GomsTwoButtonDialog.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/design-system/src/main/java/com/goms/design_system/component/shimmer/shimmerEffect.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/LinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/text/RowLinkText.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/util/DevicePreviews.kt
  core/design-system/src/main/java/com/goms/design_system/util/ThemeDevicePreviews.kt
  core/design-system/src/main/java/com/goms/design_system/util/ThemePreviews.kt
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  core/ui/src/main/java/com/goms/ui/SwitchSelectorBottomSheet.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/main/src/main/java/com/goms/main/AdminMenuScreen.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeResultDialog.kt
  feature/re-password/src/main/java/com/goms/re_password/PasswordCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/WithdrawalScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature, ⚡️Performance
