Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-04, with the labels that each got.

#141 🔀 :: (#121) - add alarm on off function
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  core/data/src/main/java/com/goms/data/repository/notification/NotificationRepository.kt
  core/data/src/main/java/com/goms/data/repository/notification/NotificationRepositoryImpl.kt
  core/datastore/src/main/java/com/goms/datastore/SettingDataSource.kt
  core/domain/src/main/java/com/goms/domain/notification/DeleteDeviceTokenUseCase.kt
  core/domain/src/main/java/com/goms/domain/setting/SetAlarmUseCase.kt
  core/network/src/main/java/com/goms/network/api/NotificationAPI.kt
  core/network/src/main/java/com/goms/network/datasource/notification/NotificationDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/notification/NotificationDataSourceImpl.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/navigation/SettingNavigation.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#143 🔀 :: (#142) - change app name
  app/src/main/res/values/strings.xml
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#145 🔀 :: (#144) - auto login
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/goms/domain/auth/TokenRefreshUseCase.kt
  core/network/src/main/java/com/goms/network/api/AuthAPI.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#155 🔀 :: (#155) - release 1.0.2
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  app/src/main/res/values/strings.xml
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/com/goms/data/repository/notification/NotificationRepository.kt
  core/data/src/main/java/com/goms/data/repository/notification/NotificationRepositoryImpl.kt
  core/datastore/src/main/java/com/goms/datastore/SettingDataSource.kt
  core/design-system/src/main/java/com/goms/design_system/component/timer/CountdownTimer.kt
  core/design-system/src/main/res/drawable/ic_qrcode_load.xml
  core/domain/src/main/java/com/goms/domain/auth/TokenRefreshUseCase.kt
  core/domain/src/main/java/com/goms/domain/notification/DeleteDeviceTokenUseCase.kt
  core/domain/src/main/java/com/goms/domain/setting/SetAlarmUseCase.kt
  core/network/src/main/java/com/goms/network/api/AuthAPI.kt
  core/network/src/main/java/com/goms/network/api/NotificationAPI.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/datasource/notification/NotificationDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/notification/NotificationDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/login/src/main/java/com/goms/login/LoginScreen.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/component/QrcodeGenerateTimer.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/navigation/SettingNavigation.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#153 🔀 :: (#146) - in app update
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, ✨ Feature

#149 🔀 :: (#148) - add dropdown default text
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectGenderDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectMajorDropDown.kt
Labels: 0️⃣ Priority: Critical, 🔨 Refector

#157 🔀 :: (#156) - release 1.1.0
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#158 🔀 :: (#157) - release 1.1.0
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepository.kt
  core/data/src/main/java/com/goms/data/repository/account/AccountRepositoryImpl.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/ProfileBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/dropdown/GomsDropdown.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_default_image.xml
  core/design-system/src/main/res/drawable/ic_gallery_add.xml
  core/domain/src/main/java/com/goms/domain/account/DeleteProfileImageUseCase.kt
  core/domain/src/main/java/com/goms/domain/account/SetProfileImageUseCase.kt
  core/domain/src/main/java/com/goms/domain/account/UpdateProfileImageUseCase.kt
  core/network/src/main/java/com/goms/network/api/AccountAPI.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/account/AccountDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectGenderDropDown.kt
  feature/sign-up/src/main/java/com/goms/sign_up/component/SelectMajorDropDown.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#160 🔀 :: (#159) - changing user permissions changing bottom sheet
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/model/src/main/java/com/goms/model/enum/BlackList.kt
  core/ui/src/main/java/com/goms/ui/SwitchSelectorBottomSheet.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
Labels: 0️⃣ Priority: Critical, 🎨 Publishing

#163 🔀 :: (#162) - change the color of the text field
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#165 🔀 :: (#164) - change if to when
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector

#168 🔀 :: (#167) - detach uistate package
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/login/src/main/java/com/goms/login/viewmodel/uistate/LoginUiState.kt
  feature/login/src/main/java/com/goms/login/viewmodel/uistate/SaveTokenUiState.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetLateListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetLateRankListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetOutingCountUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetOutingListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetProfileUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetStudentListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/OutingSearchUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/StudentSearchUiState.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/uistate/GetOutingUUIDUiState.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/uistate/OutingUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/EmailCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/PasswordNumberScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/RePasswordUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/SendNumberUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/VerifyNumberUiState.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/GetProfileUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/LogoutUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/ProfileImageUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/SetThemeUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SendNumberUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SignUpUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/VerifyNumberUiState.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector

#171 🔀 :: (#170) - update version 1.1.1
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#172 🔀 :: (#172) - release 1.1.1
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  core/design-system/src/main/java/com/goms/design_system/component/bottomsheet/SelectorBottomSheet.kt
  core/design-system/src/main/java/com/goms/design_system/component/button/GomsSwitchButton.kt
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/model/src/main/java/com/goms/model/enum/BlackList.kt
  core/ui/src/main/java/com/goms/ui/SwitchSelectorBottomSheet.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/login/src/main/java/com/goms/login/viewmodel/uistate/LoginUiState.kt
  feature/login/src/main/java/com/goms/login/viewmodel/uistate/SaveTokenUiState.kt
  feature/main/src/main/java/com/goms/main/LateListScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/OutingStatusScreen.kt
  feature/main/src/main/java/com/goms/main/StudentManagementScreen.kt
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/MainOutingCard.kt
  feature/main/src/main/java/com/goms/main/component/MainProfileCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetLateListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetLateRankListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetOutingCountUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetOutingListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetProfileUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/GetStudentListUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/OutingSearchUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/StudentSearchUiState.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeGenerateScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/uistate/GetOutingUUIDUiState.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/uistate/OutingUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/EmailCheckScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/PasswordNumberScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/RePasswordUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/SendNumberUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/VerifyNumberUiState.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/SettingViewModel.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/GetProfileUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/LogoutUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/ProfileImageUiState.kt
  feature/setting/src/main/java/com/goms/setting/viewmodel/uistate/SetThemeUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SendNumberUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SignUpUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/VerifyNumberUiState.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#174 🔀 :: (#173) - change server url
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#175 🔀 :: (#174) - release 1.1.2
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#176 🔀 :: (#169) - apply firebase crachlytics
  app/build.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidFirebaseConventionPlugin.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: 1️⃣ Priority: High, ✨ Feature

#177 🔀 :: (#152) - change qrcode dialog text
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/navigation/QrcodeNavigation.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/uistate/GetProfileUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#179 🔀 :: (#178) - update version 1.1.3
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#180 🔀 :: (#180) - release 1.1.3
  app/build.gradle.kts
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidFirebaseConventionPlugin.kt
  build.gradle.kts
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/navigation/QrcodeNavigation.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/uistate/GetProfileUiState.kt
  gradle/libs.versions.toml
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#182 🔀 :: (#181) - fix wrong qrcode scan error
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
  feature/qrcode/src/main/java/com/goms/qrcode/viewmodel/QrcodeViewModel.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#188 🔀 :: (#187) - manage string data except UI
  app/src/main/java/com/goms/goms_android_v2/GomsNotification.kt
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  core/model/src/main/java/com/goms/model/util/Regex.kt
  core/model/src/main/java/com/goms/model/util/ResourceKeys.kt
  core/network/src/main/java/com/goms/network/api/AccountAPI.kt
  core/network/src/main/java/com/goms/network/api/AuthAPI.kt
  core/network/src/main/java/com/goms/network/api/CouncilAPI.kt
  core/network/src/main/java/com/goms/network/api/LateAPI.kt
  core/network/src/main/java/com/goms/network/api/NotificationAPI.kt
  core/network/src/main/java/com/goms/network/api/OutingAPI.kt
  core/network/src/main/java/com/goms/network/di/RequestUrls.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  core/ui/src/main/java/com/goms/ui/isStrongEmail.kt
  core/ui/src/main/java/com/goms/ui/isStrongPassword.kt
  core/ui/src/main/java/com/goms/ui/isValidEmail.kt
  core/ui/src/main/java/com/goms/ui/isValidPassword.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/PasswordNumberScreen.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/NumberScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector

#190 🔀 :: (#189) - change to an exception handling view model
  core/model/src/main/java/com/goms/model/util/Regex.kt
  feature/find-password/src/main/java/com/goms/find_password/EmailCheckScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/FindPasswordScreen.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/FindPasswordViewmodel.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/uistate/FindPasswordUiState.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/uistate/SendNumberUiState.kt
  feature/find-password/src/main/java/com/goms/find_password/viewmodel/uistate/VerifyNumberUiState.kt
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
  feature/login/src/main/java/com/goms/login/viewmodel/LoginViewModel.kt
  feature/login/src/main/java/com/goms/login/viewmodel/uistate/LoginUiState.kt
  feature/login/src/main/java/com/goms/login/viewmodel/uistate/SaveTokenUiState.kt
  feature/re-password/src/main/java/com/goms/re_password/RePasswordScreen.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/RePasswordViewmodel.kt
  feature/re-password/src/main/java/com/goms/re_password/viewmodel/uistate/RePasswordUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/PasswordScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/SignUpScreen.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/SignUpViewModel.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SendNumberUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/SignUpUiState.kt
  feature/sign-up/src/main/java/com/goms/sign_up/viewmodel/uistate/VerifyNumberUiState.kt
Labels: 2️⃣ Priortiy: Medium, 🔨 Refector

#192 🔀 :: (#191) - change the return from outing dialog text
  feature/qrcode/src/main/java/com/goms/qrcode/QrcodeScanScreen.kt
Labels: 1️⃣ Priority: High, ⚡️ Simple

#194 🔀 :: (#193) - publishing administrator menu page
  app/src/main/java/com/goms/goms_android_v2/navigation/GomsNavHost.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_clock.xml
  core/design-system/src/main/res/drawable/ic_menu.xml
  core/design-system/src/main/res/drawable/ic_outing.xml
  core/ui/src/main/java/com/goms/ui/GomsTopBar.kt
  feature/main/src/main/java/com/goms/main/AdminMenuScreen.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/component/AdminMenuList.kt
  feature/main/src/main/java/com/goms/main/component/AdminMenuText.kt
  feature/main/src/main/java/com/goms/main/navigation/MainNavigation.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#196 🔀 :: (#195) - change admin profile change button color
  core/design-system/src/main/res/drawable/ic_change_profile_admin.xml
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SettingProfileCard.kt
Labels: 2️⃣ Priortiy: Medium, 🐞 Bug, 🎨 Publishing

#198 🔀 :: (#197) - remove access token from logout header
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
Labels: 1️⃣ Priority: High, 🔨 Refector, ⚡️ Simple

#203 🔀 :: (#202) - apply r8
  app/proguard-rules.pro
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: 1️⃣ Priority: High, 🌏 Deploy, ✨ Feature

#205 🔀 :: (#204) - disconnecte the interceptor
  app/src/main/java/com/goms/goms_android_v2/MainActivityViewModel.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/goms/data/repository/auth/AuthRepositoryImpl.kt
  core/domain/src/main/java/com/goms/domain/auth/TokenRefreshUseCase.kt
  core/network/src/main/java/com/goms/network/api/AuthAPI.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSource.kt
  core/network/src/main/java/com/goms/network/datasource/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/goms/network/di/NetworkModule.kt
  core/network/src/main/java/com/goms/network/di/RequestUrls.kt
  core/network/src/main/java/com/goms/network/util/AuthInterceptor.kt
  core/network/src/main/java/com/goms/network/util/TokenAuthenticator.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature, ⚡️Performance
