Repository team-haribo/GOMS-Android-V2, pull requests merged in 2024-05, with the labels that each got.

#207 (#206) - reissue token upon pull refresh
  app/src/main/java/com/goms/goms_android_v2/MainActivity.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/SaveTokenUiState.kt
  feature/main/src/main/java/com/goms/main/viewmodel/uistate/TokenRefreshUiState.kt
Labels: 0️⃣ Priority: Critical, ✨ Feature

#210 🔀 :: (#208) - apply password show hide
  core/design-system/src/main/java/com/goms/design_system/component/textfield/GomsTextField.kt
  core/design-system/src/main/java/com/goms/design_system/icon/GomsIcon.kt
  core/design-system/src/main/res/drawable/ic_invisible.xml
  core/design-system/src/main/res/drawable/ic_visible.xml
  feature/login/src/main/java/com/goms/login/InputLoginScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#213 🔀 :: (#212) - change the image if there are no result
  feature/main/src/main/java/com/goms/main/component/LateList.kt
  feature/main/src/main/java/com/goms/main/component/LateListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/MainLateCard.kt
  feature/main/src/main/java/com/goms/main/component/OutingListEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/OutingStatusList.kt
  feature/main/src/main/java/com/goms/main/component/RankEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/SearchEmptyText.kt
  feature/main/src/main/java/com/goms/main/component/StudentManagementList.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
Labels: 1️⃣ Priority: High, 🎨 Publishing

#215 🔀 :: (#214) - main-page-outgoing-status-limitations-on-number-of-people
  feature/main/src/main/java/com/goms/main/MainScreen.kt
Labels: 0️⃣ Priority: Critical, 🎨 Publishing, 🔨 Refector

#217 🔀 :: (#216) - write README.md
  LICENSE
  README.md
Labels: 3️⃣ Priority: Low, 📄 Docs

#221 🔀 :: (#220) - managing string data with enum class
  app/src/main/java/com/goms/goms_android_v2/ui/GomsApp.kt
  core/datastore/src/main/java/com/goms/datastore/SettingDataSource.kt
  core/design-system/src/main/java/com/goms/design_system/theme/GomsTheme.kt
  core/model/src/main/java/com/goms/model/enum/Switch.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
  feature/setting/src/main/java/com/goms/setting/component/SelectThemeDropDown.kt
Labels: 3️⃣ Priority: Low, 🔨 Refector

#223 🔀 :: (#222) - fix setting switch button double click error
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#211 🔀 :: (#209) - improve bar code recognition performance
  feature/qrcode/src/main/java/com/goms/qrcode/util/QrcodeScanner.kt
Labels: 0️⃣ Priority: Critical, ⚡️Performance

#226 🔀 :: (#224) - change-qr-scan-guide
  core/design-system/src/main/res/drawable/ic_qr_scan_guide.xml
Labels: 0️⃣ Priority: Critical, 🎨 Publishing, ⚡️ Simple

#227 🔀 :: (#225) - add current time feature to user
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  feature/main/src/main/java/com/goms/main/MainScreen.kt
  feature/main/src/main/java/com/goms/main/viewmodel/MainViewModel.kt
  feature/setting/src/main/java/com/goms/setting/SettingScreen.kt
Labels: 1️⃣ Priority: High, ✨ Feature
